List<Map> activities =[
        {
            "Activitiy Name":"PROGRAMMING CLASS",
            "Time":"9:20am : 10:40pm",
            "Total Pomodoro Sessions":"10"
        },
        {
            "Activitiy Name":"ANOTHER ACTIVITIE",
            "Time":"6:20am : 10:40pm",
            "Total Pomodoro Sessions":"1"
        },
        {
            "Activitiy Name":"MORE ACTIVITIES",
            "Time":"19:20am : 10:40pm",
            "Total Pomodoro Sessions":"2"
        },
        {
            "Activitiy Name":"FUN FUN ACTIVITIES",
            "Time":"9:20am : 22:40pm",
            "Total Pomodoro Sessions":"50"
        }
    ];